name: flutter_fir_e_commerce
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cloud_firestore: ^3.4.6
  cloud_firestore_odm: ^1.0.0-dev.28
  equatable: ^2.0.5
  firebase_core: ^1.21.1
  firebase_storage: ^10.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_image_compress: ^1.1.2
  flutter_localizations:
    sdk: flutter
  fpdart: ^0.2.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  hive: ^2.2.3
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  path: ^1.8.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
