// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7cu-td1G4Eqh09gf0mEZDKw9bRHJIfiw',
    appId: '1:22218936047:web:cbdba78d6dd7771ac4d51a',
    messagingSenderId: '22218936047',
    projectId: 'flutter-fir-e-commerce',
    authDomain: 'flutter-fir-e-commerce.firebaseapp.com',
    storageBucket: 'flutter-fir-e-commerce.appspot.com',
    measurementId: 'G-6K4CQM4JND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI4E8t-2VlwCipU9-l_ABwss4eSwZFzIw',
    appId: '1:22218936047:android:964fcd08e18f0cb0c4d51a',
    messagingSenderId: '22218936047',
    projectId: 'flutter-fir-e-commerce',
    storageBucket: 'flutter-fir-e-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC41sAs7Uc17CUkkskyhPU8eTv67Q6U_rk',
    appId: '1:22218936047:ios:86b259c0b2644147c4d51a',
    messagingSenderId: '22218936047',
    projectId: 'flutter-fir-e-commerce',
    storageBucket: 'flutter-fir-e-commerce.appspot.com',
    iosClientId: '22218936047-1lsio0d44oeahe19mu0fb7kva1pfbhqh.apps.googleusercontent.com',
    iosBundleId: 'com.custom.me.flutter-fir-e-commerce',
  );
}
