// This file is "main.dart"
import 'dart:typed_data';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'image.freezed.dart';

@freezed
class ImageRepresentation with _$ImageRepresentation {
  const factory ImageRepresentation.memory(Uint8List bytes) = MemoryImage;
  const factory ImageRepresentation.url(String imageUrl) = UrlImage;
}
